feature_extract_enable : 0
point_filter_num : 1
max_iteration : 4
dense_map_enable : 0
filter_size_surf : 0.1
filter_size_map : 0.1
cube_side_length : 1000
debug : 0
min_img_count : 150000
grid_size : 40
patch_size : 8
img_enable : 0
lidar_enable : 1
uwb_enable: 0
gnss_enable: 0
outlier_threshold : 78 # 78 100 156
img_point_cov : 1000 #100
laser_point_cov : 0.001  #0.001 
cam_fx: 453.483063
cam_fy: 453.254913
cam_cx: 318.908851
cam_cy: 234.238189

udb_comm_enable: 0
udp_ip: "192.168.109.102" # "192.168.8.156" # "BROADCAST"
udp_port: "8000"


common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/mems_data"
    gnss_topic:  "/GGA_Data"

preprocess:
    lidar_type: 2               # Livox Avia LiDAR
    scan_line: 32
    blind: 1 # blind x m disable

mapping:
    imu_en: true
    imu_int_frame:  30  #2000  #30    uwb需要1000数据(20s)初始化  20*100=2000
    acc_cov: 0.1  #0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001   #
    b_gyr_cov: 0.0001
    fov_degree:    180
    # extrinsic_T: [ 0.0, 0.0, -0.0 ]
    # extrinsic_R: [ 1, 0, 0,
    #                0, 1, 0,
    #                0, 0, 1]
    #extrinsic_T: [ -0.023005, -0.111058, 0.1]
    lever: [-0.02, -0.26, 0.13]
    zupt_std: [0.05, 0.05, 0.05]
    nhc_std: [0.2,0.1]
    # extrinsic_T: [ -0.023005, -0.05, 0.1]
    # extrinsic_R: [ 0, -1, 0, 
    #                              1, 0, 0, 
    #                              0, 0, 1]
    # extrinsic_T: [ -0.0, -0.0, 0.28]
    # extrinsic_R: [ 1, 0, 0, 
    #                              0, 1, 0, 
    #                              0, 0, 1]
    extrinsic_T: [-0.1,0.338,0.534]
    extrinsic_R: [ 0,-1,0,
                   1, 0, 0, 
                0, 0, 1]
voxel:
    voxel_map_en: true
    pub_plane_en: false
    dept_err: 0.02   #0.02
    beam_err: 0.05  #0.05           #标准差  单位为度
    min_eigen_value: 0.01
    match_s: 0.9
    sigma_num: 3
    voxel_size: 3
    layer: 2

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /left_camera/image
    #xiyuan
    # Rcl: [0.00162756,-0.999991,0.00390957,
    #      -0.0126748,-0.00392989,-0.999912,
    #       0.999918,0.00157786,-0.012681]
    # Pcl: [0.0409257, 0.0318424, -0.0927219]
    Rcl: [ 0.000910902,   -0.999994,  0.00343779, # new extrinsic
          -0.0101394,     -0.00344672,   -0.999943,
           0.999948,       0.000875869,  -0.0101423]
    Pcl: [0.051708, -0.004601, -0.023075]
    
publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame
    effect_point_pub: true

pcd_save:
    pcd_save_en: false
    type: 0                      # 0 - World Frame, 1 - Body Frame;
    interval: -1                  # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
    img_save_en: false
    rot_dist: 0.0 # 0.05
    pos_dist: 0.0 # 0.15
    interval: 1
